# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUILD_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

from model.downloader import DownloadURL
import json

class Ui_MainWindow(object):
    def __init__(self):
        self.folder_instloc = ""
        self.location_ytdlp = ""
        self.location_ffmpeg = ""

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 300))
        MainWindow.setMaximumSize(QtCore.QSize(500, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("view/GUILD.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_cmd = QtWidgets.QTextEdit(self.centralwidget)
        self.text_cmd.setGeometry(QtCore.QRect(10, 140, 481, 151))
        self.text_cmd.setReadOnly(True)
        self.text_cmd.setObjectName("text_cmd")
        self.btn_download = QtWidgets.QPushButton(self.centralwidget)
        self.btn_download.setGeometry(QtCore.QRect(320, 100, 171, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_download.setFont(font)
        self.btn_download.setObjectName("btn_download")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 47))
        self.layoutWidget.setObjectName("layoutWidget")
        self.layout_top = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.layout_top.setContentsMargins(0, 0, 0, 0)
        self.layout_top.setObjectName("layout_top")
        self.label_url = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_url.setFont(font)
        self.label_url.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_url.setAlignment(QtCore.Qt.AlignCenter)
        self.label_url.setObjectName("label_url")
        self.layout_top.addWidget(self.label_url)
        self.line_url = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_url.setObjectName("line_url")
        self.layout_top.addWidget(self.line_url)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 70, 176, 52))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.layout_left = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.layout_left.setContentsMargins(0, 0, 0, 0)
        self.layout_left.setObjectName("layout_left")
        self.horizontal_layout_left1 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_left1.setSpacing(17)
        self.horizontal_layout_left1.setObjectName("horizontal_layout_left1")
        self.label_format = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_format.setFont(font)
        self.label_format.setObjectName("label_format")
        self.horizontal_layout_left1.addWidget(self.label_format)
        self.box_format = QtWidgets.QComboBox(self.layoutWidget1)
        self.box_format.setObjectName("box_format")
        self.box_format.addItem("")
        self.box_format.addItem("")
        self.box_format.addItem("")
        self.box_format.addItem("")
        self.box_format.addItem("")
        self.horizontal_layout_left1.addWidget(self.box_format)
        self.layout_left.addLayout(self.horizontal_layout_left1)
        self.horizontal_layout_left2 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_left2.setContentsMargins(-1, -1, 0, 0)
        self.horizontal_layout_left2.setSpacing(8)
        self.horizontal_layout_left2.setObjectName("horizontal_layout_left2")
        self.label_quality = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_quality.setFont(font)
        self.label_quality.setObjectName("label_quality")
        self.horizontal_layout_left2.addWidget(self.label_quality)
        self.box_quality = QtWidgets.QComboBox(self.layoutWidget1)
        self.box_quality.setEnabled(True)
        self.box_quality.setObjectName("box_quality")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.box_quality.addItem("")
        self.horizontal_layout_left2.addWidget(self.box_quality)
        self.layout_left.addLayout(self.horizontal_layout_left2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(210, 100, 81, 21))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontal_layout_inst2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontal_layout_inst2.setContentsMargins(0, 0, 0, 0)
        self.horizontal_layout_inst2.setObjectName("horizontal_layout_inst2")
        self.label_ytdlp = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ytdlp.setFont(font)
        self.label_ytdlp.setObjectName("label_ytdlp")
        self.horizontal_layout_inst2.addWidget(self.label_ytdlp)
        self.btn_ytdlp = QtWidgets.QToolButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_ytdlp.setFont(font)
        self.btn_ytdlp.setObjectName("btn_ytdlp")
        self.horizontal_layout_inst2.addWidget(self.btn_ytdlp)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(210, 70, 81, 21))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontal_layout_inst1 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontal_layout_inst1.setContentsMargins(0, 0, 0, 0)
        self.horizontal_layout_inst1.setObjectName("horizontal_layout_inst1")
        self.label_ffmpeg = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ffmpeg.setFont(font)
        self.label_ffmpeg.setObjectName("label_ffmpeg")
        self.horizontal_layout_inst1.addWidget(self.label_ffmpeg)
        self.btn_ffmpeg = QtWidgets.QToolButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_ffmpeg.setFont(font)
        self.btn_ffmpeg.setObjectName("btn_ffmpeg")
        self.horizontal_layout_inst1.addWidget(self.btn_ffmpeg)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(320, 70, 171, 21))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontal_layout_r1 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontal_layout_r1.setContentsMargins(0, 0, 0, 0)
        self.horizontal_layout_r1.setObjectName("horizontal_layout_r1")
        self.label_where = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_where.setFont(font)
        self.label_where.setObjectName("label_where")
        self.horizontal_layout_r1.addWidget(self.label_where)
        self.btn_where = QtWidgets.QToolButton(self.layoutWidget3)
        self.btn_where.setObjectName("btn_where")
        self.horizontal_layout_r1.addWidget(self.btn_where)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GUILD"))
        self.btn_download.setText(_translate("MainWindow", "Скачать"))
        self.label_url.setText(_translate("MainWindow", "URL Ссылка:"))
        self.label_format.setText(_translate("MainWindow", "Формат Музыки:"))
        self.box_format.setItemText(0, _translate("MainWindow", "mp3"))
        self.box_format.setItemText(1, _translate("MainWindow", "m4a"))
        self.box_format.setItemText(2, _translate("MainWindow", "flac"))
        self.box_format.setItemText(3, _translate("MainWindow", "opus"))
        self.box_format.setItemText(4, _translate("MainWindow", "vorbis"))
        self.label_quality.setText(_translate("MainWindow", "Качество Музыки:"))
        self.box_quality.setItemText(0, _translate("MainWindow", "0"))
        self.box_quality.setItemText(1, _translate("MainWindow", "1"))
        self.box_quality.setItemText(2, _translate("MainWindow", "2"))
        self.box_quality.setItemText(3, _translate("MainWindow", "3"))
        self.box_quality.setItemText(4, _translate("MainWindow", "4"))
        self.box_quality.setItemText(5, _translate("MainWindow", "5"))
        self.box_quality.setItemText(6, _translate("MainWindow", "6"))
        self.box_quality.setItemText(7, _translate("MainWindow", "7"))
        self.box_quality.setItemText(8, _translate("MainWindow", "8"))
        self.box_quality.setItemText(9, _translate("MainWindow", "9"))
        self.box_quality.setItemText(10, _translate("MainWindow", "10"))
        self.label_ytdlp.setText(_translate("MainWindow", "yt-dlp:"))
        self.btn_ytdlp.setText(_translate("MainWindow", "..."))
        self.label_ffmpeg.setText(_translate("MainWindow", "ffmpeg:"))
        self.btn_ffmpeg.setText(_translate("MainWindow", "..."))
        self.label_where.setText(_translate("MainWindow", "Место установки:"))
        self.btn_where.setText(_translate("MainWindow", "..."))

        self.btn_download.clicked.connect(self.download)
        self.btn_where.clicked.connect(self.installation_location)
        self.btn_ffmpeg.clicked.connect(self.ffmpeg_location)
        self.btn_ytdlp.clicked.connect(self.ytdlp_location)

    def download(self):
        url = self.line_url.text()
        format_box = self.box_format.currentText()
        quality_box = self.box_quality.currentText()
        
        downloader = DownloadURL()
        downloader.set_music(url, quality_box, format_box)

        def log(text, source):
            if source == 'error':
                self.text_cmd.append(f"{text}")
            else:
                self.text_cmd.append(text)

        downloader.download(on_output=log)

    def installation_location(self):
        folder_instloc = QFileDialog.getExistingDirectory()

        if folder_instloc:
            DownloadURL().input_json(1, folder_instloc)
            self.text_cmd.append(f"Место установки: {folder_instloc}")
        else:
            self.text_cmd.append("Выбор места установки отменен")
    
    def ffmpeg_location(self):
        location_ffmpeg = QFileDialog.getOpenFileName()[0]

        if location_ffmpeg:
            DownloadURL().input_json(3, location_ffmpeg)
            self.text_cmd.append(f"Файл ffmpeg: {location_ffmpeg}")
        else:
            self.text_cmd.append("Выбор места установки ffmpeg отменен")
    
    def ytdlp_location(self):
        location_ytdlp = QFileDialog.getOpenFileName()[0]

        if location_ytdlp:
            DownloadURL().input_json(2, location_ytdlp)
            self.text_cmd.append(f"Файл yt-dlp: {location_ytdlp}")
        else:
            self.text_cmd.append("Выбор места установки yt-dlp отменен")
